services:

  mqtt-broker:
    image: emqx:latest
    # user: "1001"
    environment:
      - "EMQX_NAME=${EMQX_NAME}"
      - "EMQX_HOST=${EMQX_HOST}"
      - "EMQX_NODE_NAME=${EMQX_NAME}@${EMQX_HOSTIP}"
      - "EMQX_NODE_COOKIE=${EMQX_NODE_COOKIE}"

    healthcheck:
      test: [ "CMD", "/opt/emqx/bin/emqx", "ctl", "status" ]
      interval: 5s
      timeout: 25s
      retries: 5

    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - /etc/localtime:/etc/localtime:ro #Sync timezone with host
      - emqx-data:/opt/emqx/data
      # - emqx-log:/opt/emqx/log
      # - $PWD/etc:/opt/emqx/etc
    restart: always
    networks:
      - data-network

  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - /etc/localtime:/etc/localtime:ro #Sync timezone with host
      - influxdb-data:/var/lib/influxdb2:rw

    restart: unless-stopped
    env_file:
      - .env
    networks:
      - data-network

  grafana:
    image: grafana/grafana:latest
    # user: "1000"
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro #Sync timezone with host
      - grafana-data:/var/lib/grafana:rw
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_ADMIN_USERNAME
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - data-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - /etc/localtime:/etc/localtime:ro #Sync timezone with host
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - data-network

  mqtt-agent:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "python main.py"
    networks:
      - data-network
    volumes:
      - /etc/localtime:/etc/localtime:ro #Sync timezone with host
      - ./config:/app/config
      - ./logs:/app/logs

networks:
  data-network:
    driver: bridge

volumes:
  influxdb-data:
  emqx-data:
  grafana-data:
