secrets_filepath = ".env"

[mqtt.broker]
hostname = "docker-mqtt-metrics-manager-mqtt-broker-1"
# hostname = "localhost"
port = 1_883

[mqtt.node_network]
topic_structure = "node_id/measurement/location/field*"
enable_prometheus_server = false
prometheus_port = 8_000

[mqtt.client]
node_id = "pi-dev"
subscribe_topics = ["+/environment/#"]
subscribe_qos = 0
