
secrets_filepath = ".env"

[mqtt.broker]
hostname = "10.0.0.4"
port = 1_883

[mqtt.node_network]
#topic_structure = "location/measurement/field*"
enable_prometheus_server = false
prometheus_port = 8_000

[mqtt.client]
node_id = "environment-node-1"
